#url: https://conchoecia.github.io
#baseurl: /nccb_website/
# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: nccb.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Site settings
title: NCCB
email: dts@usc.edu
description: "The Northern California Computational Biology student group."

# Color settings (hex-codes without the leading hash-tag)
color:
  link: CBA72B
  primary: fed136
  secondary: fec503
  secondary-dark: 000

# Team names, titles and social links
people:
- name: Carlos Fernando Buen Abad Najar
  pic: carlos
  position: Outreach
  description: UCB PhD Y3

- name: Darrin Schultz
  pic: darrin
  position: outreach/webmaster
  description: UCSC BMEB PhD Y3
  social:
    - title: twitter
      url: https://twitter.com/conchoecia
    - title: google
      url: http://scholar.google.com/citations?user=k2n_5QoAAAAJ
    - title: github
      url: https://github.com/conchoecia

- name: Colleen Bosworth
  pic: colleen
  position: logistics coordinator
  description: UCSC BMEB PhD Y2

- name: Ashley Wong
  pic: ashley
  position: speaker coordinator
  description: UCSC BMEB undergrad

- name: Alison Tang
  pic: alison
  position: website
  description: UCSC BMEB PhD Y2
  social:

- name: Thomas Ng
  pic: thomas
  position: logistics
  description: UCSC BMEB PhD Y6
  social:
    - title: google
      url: https://scholar.google.com/citations?user=JJ6g0BoAAAAJ&hl=en

- name: Roger Volden
  pic: roger
  description: UCSC BMEB PhD Y2

- name: Akshar Lohith
  pic: akshar
  position: logistics
  description: UCSC BMEB PhD Y2
  social:
    - title: book
      url: https://www.researchgate.net/profile/Akshar_Lohith
    - title: linkedin-square
      url: https://www.linkedin.com/in/alohith/

- name: Matvei Khoroshkin
  pic: matvei
  position: speaker coordinator
  description: UCSF BMI PhD Y2
  social:
    - title: google
      url: https://scholar.google.com/citations?user=nruhBWkAAAAJ&hl=en

- name: Brandon Saint-John
  pic: brandon
  position: logistics
  description: UCSF BMI PhD Y2
  social:
    - title: google
      url: https://scholar.google.com/citations?user=nruhBWkAAAAJ&hl=en

- name: Lucas Waldburger
  pic: lucas
  description: UCB undergrad Y2




# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
    - title: facebook
      url: https://www.facebook.com/NorCalCompBio/
    - title: eventbrite
      url: https://www.eventbrite.com/e/northern-california-computational-biology-student-symposium-2017-tickets-35058505935 

# Build settings
markdown: kramdown
permalink: pretty
