#url: https://conchoecia.github.io
#baseurl: /nccb_website/
# Your website URL (e.g. https://barryclark.github.io or https://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: nccb.io

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your User repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Site settings
title: NCCB
email: nccbsymposium@gmail.com
description: "The Northern California Computational Biology student group."

# Color settings (hex-codes without the leading hash-tag)
color:
  link: CBA72B
  primary: 006fb8
  secondary: 00a21a
  secondary-dark: 000

# Team names, titles and social links
people:

- name: Daniel Asarnow
  pic: daniel
  position: Communication
  description: UCSF iPQB PhD Y5
  social:
    - title: github
      url: https://github.com/asarnow

- name: Matt Jones
  pic: mattjones
  position: Communication
  description: UCSF iPQB PhD Y2
  social:
    - title: github
      url: https://github.com/mattjones315
    - title: twitter
      url: https://twitter.com/mattjonesucsf

- name: Rhondene Wint
  pic: rhondene
  position: Logistics
  description: UC Merced QSB PhD Y3
  social:
    - title: github
      url: https://github.com/rhondene
    - title: twitter
      url: https://twitter.com/R_Winty

- name: Rinaldo Catta-Preta
  pic: rinaldo
  position: Logistics
  description: UC Davis IGG PhD Y5
  social:
    - title: twitter
      url: https://twitter.com/RCatta_Preta

- name: Diana Aguilar Gomez
  pic: diana
  position: Outreach
  description: UC Berkeley Comp Bio PhD Y3
  social:
    - title: twitter
      url: https://twitter.com/dianaguilr

- name: Benjamin Yeh
  pic: benjamin
  position: Communication
  description: Stanford CS MS Y2
  social:
    - title: github
      url: https://bentyeh.github.io

- name: Yihui Zhu
  pic: yihui
  position: Outreach
  description: UC Davis IGG PhD Y5
  social:
    - title: github
      url: https://github.com/Yihui-Zhu
    - title: twitter
      url: https://twitter.com/yihuizhu12

- name: Daniela Soto
  pic: daniela
  position: Outreach
  description: UC Davis IGG PhD Y2
  social:
    - title: github
      url: https://github.com/dcsoto
    - title: twitter
      url: https://twitter.com/dcsoto_cl

- name: Connor Bybee
  pic: connor
  position: Fundraising
  description: UC Berkeley Comp Bio PhD Y4

- name: Robert Stolz
  pic:  
  position: 
  description: UC Davis IGG PhD Y4

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
    - title: facebook
      url: https://www.facebook.com/NorCalCompBio/
    - title: twitter
      url: https://twitter.com/norcalcompbio
#    - title: eventbrite
#      url: https://www.eventbrite.com/e/northern-california-computational-biology-student-symposium-2017-tickets-35058505935

# Build settings
markdown: kramdown
permalink: pretty

# Industry panel speakers
panel:
- name: Kjiersten Fagnan
  pic: fagnan
  org: Joint Genome Institute 
  position: Chief Information Officer

- name: Alex Colavin
  pic: colavin
  org: Invitae Corporation
  position: Lead of Technical Development, Clinical Sciences and Interpretation

- name: Michael Becich
  pic: becich
  org: Octave Bioscience
  position: Platform Insights Lead

- name: David Lopez
  pic: lopez
  org: Gilead Sciences
  position: Research Bioformatics Scientist

